apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  namespace: netflix
  labels:
    app: netflix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: johntoby/netflix:2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"