apiVersion: v1
kind: Service
metadata:
  name: netflix-service
  namespace: netflix
  labels:
    app: netflix
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: netflix
